### ISSUE TITLE
Kitematic Linux Exec Terminal

### ISSUE THREAD

**Issue by ryanleesipes** [docker/kitematic#1648]
Hey guys, using Kitematic on Arch. Really able to get things working pretty well except for the Exec button. Upon clicking I get the following error:

Unhandled rejection Error: Encountered an error: Error: Command failed: /bin/sh -c /usr/bin/x-terminal-emulator -e docker exec -it ubuntu-2 sh
Unknown option -e

    at /opt/Kitematic (Alpha)-linux-x64/resources/app.asar/utils/Util.js:48:18
    at ChildProcess.exithandler (child_process.js:232:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

Screenshot Attached.

Am I missing a dependency? Just need some direction. @zedtux perhaps you have some insight here?
![screenshot from 2016-04-26 06-35-36](https://cloud.githubusercontent.com/assets/2141621/14816897/1f5946a2-0b79-11e6-8d2e-7755122465ac.png)

**Comment by zedtux** [comment]
@ryanleesipes can you post the output of the command `x-terminal-emulator --help` and also `lsb_release -a`.

**Comment by ryanleesipes** [comment]
I'm trying to use terminix as the terminal. But your question prompted me to check if it had a '-e' argument, and of course it doesn't. It features a '-x' instead. Perhaps in a future release we can pop in a way to change this flag?

I can use the command with xterm, but even gnome-terminal throws up an error:

Unhandled rejection Error: Encountered an error: Error: Command failed: /bin/sh -c /usr/bin/x-terminal-emulator -e docker exec -it mycroft-dev sh
Failed to parse arguments: Unknown option -it

Finally, I've noticed the default command to run is 'sh', it would be cool if this could be toggled to bash if the user so pleased.

**Comment by zedtux** [comment]
What Linux distro are you using?

**Comment by ryanleesipes** [comment]
Heh, Arch. So I'm on a moving target.

**Comment by bebehei** [comment]
@zedtux Thanks for the good work. I'm astonished, someone took the effort to port such a nice looking app onto linux.

This issue shows a small corner case of the differences between Ubuntu and Arch.

The file `/usr/bin/x-terminal-emulator` is usually nonexistent on ArchLinux Systems, you have to link it manually.

I manually linked it to xterm and it works like a charm:
```
ln -sT xterm /usr/bin/x-terminal-emulator
```

@ryanleesipes Where does x-terminal-emulator point to? It may be the case, that your linked terminal-emulator does not understand stand `-e`. So you have to readjust your link, to point it against xterm or some other emulator understanding `-e`.

**Comment by zedtux** [comment]
Thank you @bebehei :)
