### ISSUE TITLE
build fail on mac

### ISSUE THREAD

**Issue by ssfyn** [docker/kitematic#4064]
### Expected behavior
npm install
successful

### Actual behavior
too many errors

### Information about the Issue
```shell
$ npm install

> fsevents@1.1.3 install /Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
In file included from ../fsevents.cc:6    return node::MakeCallback(:

                 ^
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:171/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h::1171:: 1: note: note: 'MakeCallback' 'MakeCallback'has  hasbeen  beenexplicitly  explicitlymarked  markeddeprecated  deprecatedhere here

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:854:18: In file included from ../fsevents.ccwarning:: 6:
'MakeCallback'../../nan/nan.h :is869 :deprecated:18 :Use  MakeCallback(..., warningasync_context):  [-Wdeprecated-declarations]
'MakeCallback' is deprecated: Use MakeCallback(...,     return node::MakeCallback(async_context)
 [-Wdeprecated-declarations]                 ^

/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:164:1:     return node::MakeCallback(
note:                  ^
'MakeCallback' has been explicitly/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h :marked157 :deprecated1 :here 
note: 'MakeCallback' has been explicitly marked NODE_DEPRECATED("Use MakeCallback(..., async_context)",deprecated
 here^

/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded fromNODE_DEPRECATED("Use MakeCallback(..., async_context)", 
macro ^'NODE_DEPRECATED'

/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20:     __attribute__((deprecated(message))) declaratornote
:                    ^expanded
 from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1648:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1648:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fanyanan/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
5 warnings generated.
5 warnings generated.
  SOLINK_MODULE(target) Release/fse.node
sed: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/opt/local/bin/node" "/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/fanyanan/WebstormProjects/kitematic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node

> electron@1.8.2 postinstall /Users/fanyanan/WebstormProjects/kitematic/node_modules/electron
> node install.js

  TOUCH Release/obj.target/action_after_build.stamp

> Kitematic@0.17.3 postinstall /Users/fanyanan/WebstormProjects/kitematic
> npm run build


> Kitematic@0.17.3 build /Users/fanyanan/WebstormProjects/kitematic
> tsc && npm run tslint


> Kitematic@0.17.3 tslint /Users/fanyanan/WebstormProjects/kitematic
> tslint --fix --project ./tsconfig.json

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN Kitematic@0.17.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.2.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.5.0 (node_modules/app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.5.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.5.0 (node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.5.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 188 packages from 224 contributors, removed 664 packages, updated 118 packages and audited 5328 packages in 48.939s
found 160 vulnerabilities (52 low, 70 moderate, 38 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

### Steps to reproduce the behavior

  1. npm install
  2. ...

**Comment by jeanlaurent** [comment]
Hello @ssfyn what's your `node --version` ?

**Comment by ssfyn** [comment]
@jeanlaurent 10.8.0

**Comment by ssfyn** [comment]
use nodejs 9.x fixed this
