### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by AbelZheng** [docker/kitematic#4312]
### Steps to reproduce the behavior

  1. click My Images
 

[Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252 Uncaught TypeError: Cannot read property 'includes' of undefined
    at /Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252:24
    at Array.filter (native)
    at Constructor.render (/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:251:40)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.mountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent._createContentMarkup (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/bugsnag-js/src/bugsnag.js:248 [Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:744 Uncaught TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:744:52)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at ReactCompositeComponentWrapper.wrapper [as updateComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.receiveComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)
    at Object.updateChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:83:25)
    at ReactDOMComponent._updateChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277:47)
    at ReactDOMComponent.updateChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251:14)
    at ReactDOMComponent._updateDOMChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470:12)
    at ReactDOMComponent.updateComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319:10)
    at ReactDOMComponent.receiveComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303:10)
    at Object.receiveComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:642:12)
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/bugsnag-js/src/bugsnag.js:248 [Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:55 Uncaught TypeError: Cannot read property '_currentElement' of null
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:55:59)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:279:21)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56:22)
    at Object.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:119:23)
    at ReactDOMComponent.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329:28)
    at ReactDOMComponent.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481:10)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56:22)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:279:21)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56:22)
    at Object.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:119:23)
    at ReactDOMComponent.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329:28)
    at ReactDOMComponent.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481:10)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56:22)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:279:21)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56:22)
    at Object.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:119:23)
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/bugsnag-js/src/bugsnag.js:248 [Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:55 Uncaught TypeError: Cannot read property '_currentElement' of null
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:55)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56)
    at Object.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:119)
    at ReactDOMComponent.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329)
    at ReactDOMComponent.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56)
    at Object.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:119)
    at ReactDOMComponent.unmountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329)
    at ReactDOMComponent.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56)
    at ReactCompositeComponentWrapper.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279)
    at Object.unmountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56)
    at Object.updateChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:103)
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:55
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56
unmountChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:119
unmountChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56
unmountChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:119
unmountChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:329
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:481
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:279
unmountComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:56
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:103
_updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251
_updateDOMChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:83
_updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251
_updateDOMChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:83
_updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251
_updateDOMChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:83
_updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251
_updateDOMChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler…:83
_updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:277
updateChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:251
_updateDOMChildren @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:470
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:319
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:303
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:506
receiveComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:97
_updateRenderedComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:748
_performComponentUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:726
updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:642
ReactCompositeComponent_updateComponent @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
performUpdateIfNecessary @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeCompon…:539
performUpdateIfNecessary @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:115
runBatchedUpdates @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:151
perform @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:134
perform @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:134
perform @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:95
flushBatchedUpdates @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:175
ReactUpdates_flushBatchedUpdates @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70
closeAll @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:207
perform @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:148
batchedUpdates @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatching…:66
enqueueUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:215
enqueueUpdate @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:30
enqueueSetState @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdateQueue.js:208
ReactComponent.setState @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactComponent.js:69
update @ /Applications/Kitematic.app/Contents/Resources/app.asar/components/Containers.react.js:105
emit @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72
AltStore.emitChange @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/store/AltStore.js:54
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/store/AltStore.js:84
Dispatcher.$Dispatcher_invokeCallback @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:220
Dispatcher.dispatch @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:195
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/index.js:74
Alt.batchingFunction @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/index.js:58
dispatch @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/index.js:73
dispatch @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/actions/index.js:43
dispatchIdentity @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/alt/lib/utils/AltUtils.js:57
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/utils/DockerUtil.js:381
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:361
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52
done @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:246
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:44
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:358
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/utils/DockerUtil.js:370
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/dockerode/lib/container.js:72
Modem.buildPayload @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/docker-modem/lib/modem.js:270
(anonymous) @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/docker-modem/lib/modem.js:229
emitNone @ events.js:110
emit @ events.js:207
endReadableNT @ _stream_readable.js:1045
_combinedTickCallback @ internal/process/next_tick.js:138
_tickCallback @ internal/process/next_tick.js:180

**Comment by ssfyn** [comment]
#4373 fixed this

**Comment by luanshixia** [comment]
I had the same problem. Can someone merge the fix please?
