### ISSUE TITLE
Kitematic Issue in MacOs

### ISSUE THREAD

**Issue by Naveen18Git** [docker/kitematic#5032]
### Information about the Issue

1.. Kitematic is not working in MacOs.
2.. Is not responding the command.
3..  
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by VitaliKrasnik** [comment]
[Mac OS 10.14.5.] Kitematic 0.17.2 and latest versions don't show the List of docker Images
1.Download the app (any version after 0.17.2)
2.Run the application app
3. Click on 'My Images' tab
Expected result: The List of docker images is present.
Actual result: Kitematic 0.17.2 and latest versions don't show the List of docker Images

**Comment by kswope** [comment]
What a mess, every version but the beta doesn't work, at least on OSX, here is the stack trace

```
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/warning.js:48 Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.
warning @ /Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/warning.js:48
/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/bugsnag-js/src/bugsnag.js:248 [Bugsnag] Invalid API key 'undefined'
/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252 Uncaught TypeError: Cannot read property 'includes' of undefined
    at /Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:252:24
    at Array.filter (native)
    at Constructor.render (/Applications/Kitematic.app/Contents/Resources/app.asar/components/ImageCard.react.js:251:40)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.mountChildren (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent._createContentMarkup (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.mountComponent (/Applications/Kitematic.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:38:35)
```

**Comment by cilto** [comment]
This is related to the docker tag variable type issue.
Considering recent low activity in the main repo, I uploaded fixed release here: https://github.com/cilto/kitematic/releases/tag/v0.17.9-hf.1.
Please feel free to use it.
